// DN42 Network Configuration
export const networkConfig = {
  asNumber: 'AS4242421234',
  asName: 'MyAS Network',
  description: 'High-performance DN42 network infrastructure with global presence',
  establishedDate: '2024-01-15',

  ipRanges: {
    ipv4: '172.20.53.0/24',
    ipv6: 'fde4:8dba:82e1::/48',
  },

  contact: {
    email: 'noc@example.dn42',
    telegram: '@mydn42',
  },

  peeringPolicy: {
    type: 'Open',
    requirements: [
      'Valid ROA entries for all announced prefixes',
      'BGP session must support both IPv4 and IPv6',
      'Maintain at least 99% uptime',
      'Respond to network issues within 24 hours',
      'Use proper BGP communities for traffic engineering',
    ],
    preferredMethods: [
      'WireGuard (preferred)',
      'OpenVPN',
      'GRE/IPsec',
    ],
  },

  statistics: {
    totalNodes: 8,
    continentsCovered: 4,
    averageHops: 3.2,
    totalPeers: 24,
  },

  nodes: [
    {
      id: 'us-nyc-01',
      city: 'New York',
      country: 'United States',
      countryCode: 'US',
      lat: 40.7128,
      lng: -74.0060,
      hostname: 'nyc01.example.dn42',
      clearnetHost: 'nyc01.example.com',
      status: 'online',
      uptime: 99.98,
      peers: 6,
    },
    {
      id: 'eu-fra-01',
      city: 'Frankfurt',
      country: 'Germany',
      countryCode: 'DE',
      lat: 50.1109,
      lng: 8.6821,
      hostname: 'fra01.example.dn42',
      clearnetHost: 'fra01.example.com',
      status: 'online',
      uptime: 99.95,
      peers: 8,
    },
    {
      id: 'as-sgp-01',
      city: 'Singapore',
      country: 'Singapore',
      countryCode: 'SG',
      lat: 1.3521,
      lng: 103.8198,
      hostname: 'sgp01.example.dn42',
      clearnetHost: 'sgp01.example.com',
      status: 'online',
      uptime: 99.92,
      peers: 5,
    },
    {
      id: 'eu-lon-01',
      city: 'London',
      country: 'United Kingdom',
      countryCode: 'GB',
      lat: 51.5074,
      lng: -0.1278,
      hostname: 'lon01.example.dn42',
      clearnetHost: 'lon01.example.com',
      status: 'online',
      uptime: 99.97,
      peers: 7,
    },
    {
      id: 'as-tok-01',
      city: 'Tokyo',
      country: 'Japan',
      countryCode: 'JP',
      lat: 35.6762,
      lng: 139.6503,
      hostname: 'tok01.example.dn42',
      clearnetHost: 'tok01.example.com',
      status: 'online',
      uptime: 99.94,
      peers: 4,
    },
    {
      id: 'us-lax-01',
      city: 'Los Angeles',
      country: 'United States',
      countryCode: 'US',
      lat: 34.0522,
      lng: -118.2437,
      hostname: 'lax01.example.dn42',
      clearnetHost: 'lax01.example.com',
      status: 'online',
      uptime: 99.91,
      peers: 3,
    },
    {
      id: 'eu-ams-01',
      city: 'Amsterdam',
      country: 'Netherlands',
      countryCode: 'NL',
      lat: 52.3676,
      lng: 4.9041,
      hostname: 'ams01.example.dn42',
      clearnetHost: 'ams01.example.com',
      status: 'maintenance',
      uptime: 99.89,
      peers: 5,
    },
    {
      id: 'oc-syd-01',
      city: 'Sydney',
      country: 'Australia',
      countryCode: 'AU',
      lat: -33.8688,
      lng: 151.2093,
      hostname: 'syd01.example.dn42',
      clearnetHost: 'syd01.example.com',
      status: 'online',
      uptime: 99.93,
      peers: 4,
    },
  ],
};
